[cursor]
style = "Block"

[font]
# normal = { family = "MesloLGS NF", style = "Regular" }
# bold = { family = "MesloLGS NF", style = "Bold" }
# italic = { family = "MesloLGS NF", style = "Italic" }
# bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12

[scrolling]
history = 1000


[window]
# decorations = "none"
opacity = 0.8

[window.padding]
x = 10
y = 10
